# Generated by Django 5.2.6 on 2026-02-19 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedbadge',
            name='issuedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masjidadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_masjids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favouritemasjid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_masjids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='masjid',
            name='confidenceRecord',
        ),
        migrations.RemoveField(
            model_name='masjid',
            name='locationRecord',
        ),
        migrations.AlterField(
            model_name='confidencerecord',
            name='masjid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_record', to='centralAPI.masjid'),
        ),
        migrations.AlterField(
            model_name='favouritemasjid',
            name='masjid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='centralAPI.masjid'),
        ),
        migrations.AlterField(
            model_name='locationrecord',
            name='country',
            field=models.CharField(choices=[('AF - Islamic Republic of Afghanistan', 'AF - Islamic Republic of Afghanistan'), ('AL - Republic of Albania', 'AL - Republic of Albania'), ("DZ - People's Democratic Republic of Algeria", "DZ - People's Democratic Republic of Algeria"), ('AD - Principality of Andorra', 'AD - Principality of Andorra'), ('AO - Republic of Angola', 'AO - Republic of Angola'), ('AG - Antigua and Barbuda', 'AG - Antigua and Barbuda'), ('AR - Argentine Republic', 'AR - Argentine Republic'), ('AM - Republic of Armenia', 'AM - Republic of Armenia'), ('AU - Commonwealth of Australia', 'AU - Commonwealth of Australia'), ('AT - Republic of Austria', 'AT - Republic of Austria'), ('AZ - Republic of Azerbaijan', 'AZ - Republic of Azerbaijan'), ('BS - Commonwealth of the Bahamas', 'BS - Commonwealth of the Bahamas'), ('BH - Kingdom of Bahrain', 'BH - Kingdom of Bahrain'), ("BD - People's Republic of Bangladesh", "BD - People's Republic of Bangladesh"), ('BB - Barbados', 'BB - Barbados'), ('BY - Republic of Belarus', 'BY - Republic of Belarus'), ('BE - Kingdom of Belgium', 'BE - Kingdom of Belgium'), ('BZ - Belize', 'BZ - Belize'), ('BJ - Republic of Benin', 'BJ - Republic of Benin'), ('BT - Kingdom of Bhutan', 'BT - Kingdom of Bhutan'), ('BO - Plurinational State of Bolivia', 'BO - Plurinational State of Bolivia'), ('BA - Bosnia and Herzegovina', 'BA - Bosnia and Herzegovina'), ('BW - Republic of Botswana', 'BW - Republic of Botswana'), ('BR - Federative Republic of Brazil', 'BR - Federative Republic of Brazil'), ('BN - Brunei Darussalam', 'BN - Brunei Darussalam'), ('BG - Republic of Bulgaria', 'BG - Republic of Bulgaria'), ('BF - Burkina Faso', 'BF - Burkina Faso'), ('BI - Republic of Burundi', 'BI - Republic of Burundi'), ('CV - Republic of Cabo Verde', 'CV - Republic of Cabo Verde'), ('KH - Kingdom of Cambodia', 'KH - Kingdom of Cambodia'), ('CM - Republic of Cameroon', 'CM - Republic of Cameroon'), ('CA - Canada', 'CA - Canada'), ('CF - Central African Republic', 'CF - Central African Republic'), ('TD - Republic of Chad', 'TD - Republic of Chad'), ('CL - Republic of Chile', 'CL - Republic of Chile'), ("CN - People's Republic of China", "CN - People's Republic of China"), ('CO - Republic of Colombia', 'CO - Republic of Colombia'), ('KM - Union of the Comoros', 'KM - Union of the Comoros'), ('CG - Republic of the Congo', 'CG - Republic of the Congo'), ('CD - Democratic Republic of the Congo', 'CD - Democratic Republic of the Congo'), ('CR - Republic of Costa Rica', 'CR - Republic of Costa Rica'), ("CI - Republic of Côte d'Ivoire", "CI - Republic of Côte d'Ivoire"), ('HR - Republic of Croatia', 'HR - Republic of Croatia'), ('CU - Republic of Cuba', 'CU - Republic of Cuba'), ('CY - Republic of Cyprus', 'CY - Republic of Cyprus'), ('CZ - Czech Republic', 'CZ - Czech Republic'), ('DK - Kingdom of Denmark', 'DK - Kingdom of Denmark'), ('DJ - Republic of Djibouti', 'DJ - Republic of Djibouti'), ('DM - Commonwealth of Dominica', 'DM - Commonwealth of Dominica'), ('DO - Dominican Republic', 'DO - Dominican Republic'), ('EC - Republic of Ecuador', 'EC - Republic of Ecuador'), ('EG - Arab Republic of Egypt', 'EG - Arab Republic of Egypt'), ('SV - Republic of El Salvador', 'SV - Republic of El Salvador'), ('GQ - Republic of Equatorial Guinea', 'GQ - Republic of Equatorial Guinea'), ('ER - State of Eritrea', 'ER - State of Eritrea'), ('EE - Republic of Estonia', 'EE - Republic of Estonia'), ('SZ - Kingdom of Eswatini', 'SZ - Kingdom of Eswatini'), ('ET - Federal Democratic Republic of Ethiopia', 'ET - Federal Democratic Republic of Ethiopia'), ('FJ - Republic of Fiji', 'FJ - Republic of Fiji'), ('FI - Republic of Finland', 'FI - Republic of Finland'), ('FR - French Republic', 'FR - French Republic'), ('GA - Gabonese Republic', 'GA - Gabonese Republic'), ('GM - Republic of the Gambia', 'GM - Republic of the Gambia'), ('GE - Georgia', 'GE - Georgia'), ('DE - Federal Republic of Germany', 'DE - Federal Republic of Germany'), ('GH - Republic of Ghana', 'GH - Republic of Ghana'), ('GR - Hellenic Republic', 'GR - Hellenic Republic'), ('GD - Grenada', 'GD - Grenada'), ('GT - Republic of Guatemala', 'GT - Republic of Guatemala'), ('GN - Republic of Guinea', 'GN - Republic of Guinea'), ('GW - Republic of Guinea-Bissau', 'GW - Republic of Guinea-Bissau'), ('GY - Co-operative Republic of Guyana', 'GY - Co-operative Republic of Guyana'), ('HT - Republic of Haiti', 'HT - Republic of Haiti'), ('HN - Republic of Honduras', 'HN - Republic of Honduras'), ('HU - Hungary', 'HU - Hungary'), ('IS - Republic of Iceland', 'IS - Republic of Iceland'), ('IN - Republic of India', 'IN - Republic of India'), ('ID - Republic of Indonesia', 'ID - Republic of Indonesia'), ('IR - Islamic Republic of Iran', 'IR - Islamic Republic of Iran'), ('IQ - Republic of Iraq', 'IQ - Republic of Iraq'), ('IE - Ireland', 'IE - Ireland'), ('IL - State of Israel', 'IL - State of Israel'), ('IT - Italian Republic', 'IT - Italian Republic'), ('JM - Jamaica', 'JM - Jamaica'), ('JP - Japan', 'JP - Japan'), ('JO - Hashemite Kingdom of Jordan', 'JO - Hashemite Kingdom of Jordan'), ('KZ - Republic of Kazakhstan', 'KZ - Republic of Kazakhstan'), ('KE - Republic of Kenya', 'KE - Republic of Kenya'), ('KI - Republic of Kiribati', 'KI - Republic of Kiribati'), ("KP - Democratic People's Republic of Korea", "KP - Democratic People's Republic of Korea"), ('KR - Republic of Korea', 'KR - Republic of Korea'), ('KW - State of Kuwait', 'KW - State of Kuwait'), ('KG - Kyrgyz Republic', 'KG - Kyrgyz Republic'), ("LA - Lao People's Democratic Republic", "LA - Lao People's Democratic Republic"), ('LV - Republic of Latvia', 'LV - Republic of Latvia'), ('LB - Lebanese Republic', 'LB - Lebanese Republic'), ('LS - Kingdom of Lesotho', 'LS - Kingdom of Lesotho'), ('LR - Republic of Liberia', 'LR - Republic of Liberia'), ('LY - State of Libya', 'LY - State of Libya'), ('LI - Principality of Liechtenstein', 'LI - Principality of Liechtenstein'), ('LT - Republic of Lithuania', 'LT - Republic of Lithuania'), ('LU - Grand Duchy of Luxembourg', 'LU - Grand Duchy of Luxembourg'), ('MG - Republic of Madagascar', 'MG - Republic of Madagascar'), ('MW - Republic of Malawi', 'MW - Republic of Malawi'), ('MY - Malaysia', 'MY - Malaysia'), ('MV - Republic of Maldives', 'MV - Republic of Maldives'), ('ML - Republic of Mali', 'ML - Republic of Mali'), ('MT - Republic of Malta', 'MT - Republic of Malta'), ('MH - Republic of the Marshall Islands', 'MH - Republic of the Marshall Islands'), ('MR - Republic of Mauritania', 'MR - Republic of Mauritania'), ('MU - Republic of Mauritius', 'MU - Republic of Mauritius'), ('MX - United Mexican States', 'MX - United Mexican States'), ('FM - Federated States of Micronesia', 'FM - Federated States of Micronesia'), ('MD - Republic of Moldova', 'MD - Republic of Moldova'), ('MC - Principality of Monaco', 'MC - Principality of Monaco'), ('MN - Mongolia', 'MN - Mongolia'), ('ME - Montenegro', 'ME - Montenegro'), ('MA - Kingdom of Morocco', 'MA - Kingdom of Morocco'), ('MZ - Republic of Mozambique', 'MZ - Republic of Mozambique'), ('MM - Republic of the Union of Myanmar', 'MM - Republic of the Union of Myanmar'), ('NA - Republic of Namibia', 'NA - Republic of Namibia'), ('NR - Republic of Nauru', 'NR - Republic of Nauru'), ('NP - Federal Democratic Republic of Nepal', 'NP - Federal Democratic Republic of Nepal'), ('NL - Kingdom of the Netherlands', 'NL - Kingdom of the Netherlands'), ('NZ - New Zealand', 'NZ - New Zealand'), ('NI - Republic of Nicaragua', 'NI - Republic of Nicaragua'), ('NE - Republic of the Niger', 'NE - Republic of the Niger'), ('NG - Federal Republic of Nigeria', 'NG - Federal Republic of Nigeria'), ('MK - Republic of North Macedonia', 'MK - Republic of North Macedonia'), ('NO - Kingdom of Norway', 'NO - Kingdom of Norway'), ('OM - Sultanate of Oman', 'OM - Sultanate of Oman'), ('PK - Islamic Republic of Pakistan', 'PK - Islamic Republic of Pakistan'), ('PA - Republic of Panama', 'PA - Republic of Panama'), ('PG - Independent State of Papua New Guinea', 'PG - Independent State of Papua New Guinea'), ('PY - Republic of Paraguay', 'PY - Republic of Paraguay'), ('PE - Republic of Peru', 'PE - Republic of Peru'), ('PH - Republic of the Philippines', 'PH - Republic of the Philippines'), ('PL - Republic of Poland', 'PL - Republic of Poland'), ('PT - Portuguese Republic', 'PT - Portuguese Republic'), ('QA - State of Qatar', 'QA - State of Qatar'), ('RO - Romania', 'RO - Romania'), ('RU - Russian Federation', 'RU - Russian Federation'), ('RW - Republic of Rwanda', 'RW - Republic of Rwanda'), ('SA - Kingdom of Saudi Arabia', 'SA - Kingdom of Saudi Arabia'), ('RS - Republic of Serbia', 'RS - Republic of Serbia'), ('SG - Republic of Singapore', 'SG - Republic of Singapore'), ('ZA - Republic of South Africa', 'ZA - Republic of South Africa'), ('ES - Kingdom of Spain', 'ES - Kingdom of Spain'), ('LK - Democratic Socialist Republic of Sri Lanka', 'LK - Democratic Socialist Republic of Sri Lanka'), ('SE - Kingdom of Sweden', 'SE - Kingdom of Sweden'), ('CH - Swiss Confederation', 'CH - Swiss Confederation'), ('SY - Syrian Arab Republic', 'SY - Syrian Arab Republic'), ('TH - Kingdom of Thailand', 'TH - Kingdom of Thailand'), ('TR - Republic of Türkiye', 'TR - Republic of Türkiye'), ('UA - Ukraine', 'UA - Ukraine'), ('AE - United Arab Emirates', 'AE - United Arab Emirates'), ('UK - United Kingdom of Great Britain and Northern Ireland', 'UK - United Kingdom of Great Britain and Northern Ireland'), ('US - United States of America', 'US - United States of America'), ('VN - Socialist Republic of Viet Nam', 'VN - Socialist Republic of Viet Nam'), ('YE - Republic of Yemen', 'YE - Republic of Yemen'), ('ZM - Republic of Zambia', 'ZM - Republic of Zambia'), ('ZW - Republic of Zimbabwe', 'ZW - Republic of Zimbabwe')], max_length=255),
        ),
        migrations.AlterField(
            model_name='locationrecord',
            name='masjid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_record', to='centralAPI.masjid'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='masjid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='centralAPI.masjid'),
        ),
        migrations.AlterField(
            model_name='verifiedbadge',
            name='masjid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='centralAPI.masjid'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'Regular User'), ('masjid_admin', 'Masjid Admin')], default='user', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='verification_docs/%Y/%m/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('masjid_admin_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='centralAPI.masjidadmin')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='RegularUser',
        ),
    ]
